

## Lab 1:FPGA and MCU Setup and Testing
The main goal of this assignment is to learn SMD in board assembly and learn how to use Lattice Radiant to write basic combinational System Verilog codes. By the end of this week's lab, I hope I can learn how to write Verilog code to test out the hardware on board, perform logic simulations in Radiant, and deepen my understanding of circuit debugging.  We are going to use on-board led to test the FPGA and also construct a functional hexadecimal 7-segment display.

**Design Approach**
In the case of testing the board, the lab manual suggested implementing a XOR and AND relationship for the ON/OFF status of two led while letting the third led shine at 2.4 Hz. I used low speed oscillators with 10k Hz and counter [11:0] so that 10k/2^12 = 2.44Hz. I also included a reset to make sure the simulation works correctly and we are not starting at a random value every time.
When working with the seven segment display, it’s good to use combinational logic to make case statements for each combination of 4 binary switches. I draw out the diagram for a seven segment display and assign seg[0] to be the segment a, seg[1] to be segment b according to the ascending order and assign free pins under FPGA for later breadboard testing.
Here is the block diagram of the top module:


**Testing Approach**
To make sure the design works as expected, I tested both through hardware breadboarding onto an actual 7 segment display led and also used QuestaSim inside Lattice Radiant. I ran through all possible combinations of 4 binary switches to ensure no edge cases are left.
Here is the schematics for the circuit of 7 segment display:
image: images\schematicslab1.jfif
This is picture for the output successful runthrough of testbenches:
Seven-segment display


XOR_AND


The design meets all the requirements that we can alternate between 0-9 and A-F through controlling the four on-off switches.
This is a picture of the board displaying on the letter F:


Number of hours spent: 18 hrs.
