---
title: "Posts Section"

author: "Amy Liu"
date: "11/01/24"
categories:
  - reflection
  - labreport
draft: false
---

**Week 9 Reflection**<br>

In the week's lecture, we discussed how to control liquid crystal displays with a digital device and how to implement the basic operation of the video graphics array protocol. Besides using FPGA, Graphics Processing Units (GPUs) are specialized digital devices designed to render images etc. for display on monitors. GPUs come with predefined pipelines specialized for rendering tasks in high speed with little latency. GPUs are what we normally used in daily applications like gaming and computing. GPU is consists of the core procussing unit to handle graphical computation, Video Memory (VRAM) to store frame buffers and textures and display output interfaces port like VGA and HDMI to connect with a monitor. Good graphics card (like NVIDIA GeForce RTX 4080) is really expensive but doesn't really have much impact on the daily usage of a computer unless you are a gamer...like me:D


